## 다중분류

데이터 출처 : https://www.kaggle.com/datasets/yasserh/wine-quality-dataset          
데이터 설명 : 와인 퀄리티 데이터셋

In [29]:
import pandas as pd

In [30]:
wine=pd.read_csv(r"C:\Users\SAMSUNG\Desktop\공부파일들\카글\WineQT.csv")
wine.drop("Id",axis=1,inplace=True)
target="quality"
feature=wine.columns.difference([target])

In [31]:
# 아래의 퀄리티를 예측하는 모델을 만들어보자
wine[target].value_counts()

quality
5    483
6    462
7    143
4     33
8     16
3      6
Name: count, dtype: int64

### step 1. 모델 선택

|모델||설명|분류기 개수|
|--|--|--|--|
|OvR/OvA|One versus Rest|특정 하나만 분류하는 모델의 만들어 결정점수가 가장 높은 값을 선택|N개(target 개수)|
|OvO|One versus One|둘 중 하나의 값만들 선택하는 binary classification 들의 조합|$\binom{n}{2}$

이진분류기로 다중분류 모델을 만들어보자

In [32]:
import sklearn.multiclass as skmul
import numpy as np
np.random.seed(10)

#### OvO 모델
* 사이킷런은 이진분류기로 다중분류 학습시 기본적으로 OvO 모델을 가정한다

In [33]:
import sklearn.svm as sksvm #svm 모델을 이용해보자
svc=sksvm.SVC(random_state=10) #파라미터는 그대로 

In [38]:
# 데이터 분류
import sklearn.model_selection as skmod
train,test=skmod.train_test_split(wine,random_state=10,stratify=wine[target],train_size=0.7)

-----

In [59]:
print(test[target][:1])

775    5
Name: quality, dtype: int64


------

In [40]:
svc.fit(X=train[feature],y=train[target])

SVC(random_state=10)

In [41]:
# 클래스 확인
svc.classes_

array([3, 4, 5, 6, 7, 8], dtype=int64)

In [50]:
svc.predict(X=test[feature][:1])

array([6], dtype=int64)

In [52]:
score=svc.decision_function(X=test[feature][:1])
print(score)
idx=score.argmax()
print(svc.classes_[idx]) # 이런 방식으로 선택

[[-0.27765236  1.83180822  4.25502015  5.27578461  3.16120585  0.75041452]]
6


#### OvR 모델

In [53]:
ovr_svc=skmul.OneVsRestClassifier(estimator=sksvm.SVC(random_state=10),n_jobs=3)

In [54]:
ovr_svc.fit(X=train[feature],y=train[target])

OneVsRestClassifier(estimator=SVC(random_state=10), n_jobs=3)

In [55]:
ovr_svc.predict(X=test[feature][:1])

array([5], dtype=int64)

In [56]:
ovr_svc.decision_function(X=test[feature][:1])

array([[-1.00047624, -0.9998454 , -0.92535609, -1.00255976, -1.00100977,
        -1.00014749]])